language: objective-c

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1
env:
  - TEST_DIR=Example/TSKitiOSTestApp

before_install:
  - cd $TEST_DIR
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool

install: travis_wait 30 pod install

xcode_workspace: TSKitiOSTestApp.xcworkspace
xcode_scheme: TSKitiOSTestApp

before_script: pwd

