language: objective-c

osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1
env:
  - TEST_DIR=Example/TSKitiOSTestApp

before_install:
  - cd $TEST_DIR
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods --no-ri --no-rdoc
  - pod repo update --silent

install: pod install

xcode_workspace: TSKitiOSTestApp.xcworkspace
xcode_scheme: TSKitiOSTestApp

